# Generated by Django 4.1 on 2023-01-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='permalink',
            field=models.CharField(max_length=12, verbose_name='Постоянная ссылка'),
        ),
    ]
