# Generated by Django 4.1 on 2023-01-23 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_quotedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='jobfile',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='position',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quotedate',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoteprice',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sitestatus',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='web',
        ),
        migrations.AddField(
            model_name='quote',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='descriptions',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название новостя'),
        ),
    ]
